import jsPDF from 'jspdf';

const GOLD = [212, 168, 67];
const DARK = [15, 15, 24];
const GRAY = [100, 100, 110];
const LIGHT = [245, 245, 240];
const WHITE = [255, 255, 255];
const RED = [239, 68, 68];
const GREEN = [34, 197, 94];

const addHeader = (doc, companyName = 'Southwest Cabs Elevator Services', title, subtitle) => {
  // Dark header background
  doc.setFillColor(...DARK);
  doc.rect(0, 0, 215, 42, 'F');

  // Gold accent bar
  doc.setFillColor(...GOLD);
  doc.rect(0, 0, 4, 42, 'F');

  // Company name
  doc.setTextColor(...GOLD);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text(companyName, 14, 16);

  // Title
  doc.setTextColor(...LIGHT);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.text(title, 14, 28);

  // Subtitle right aligned
  if (subtitle) {
    doc.setTextColor(...GRAY);
    doc.setFontSize(9);
    doc.text(subtitle, 201, 28, { align: 'right' });
  }

  // Smarterlift branding
  doc.setTextColor(...GOLD);
  doc.setFontSize(8);
  doc.text('Powered by Smarterlift', 201, 16, { align: 'right' });
};

const addFooter = (doc, pageNum, totalPages) => {
  const y = 285;
  doc.setFillColor(245, 245, 240);
  doc.rect(0, y, 215, 12, 'F');
  doc.setDrawColor(...GOLD);
  doc.setLineWidth(0.3);
  doc.line(0, y, 215, y);
  doc.setTextColor(...GRAY);
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.text('Generated by Smarterlift · smarterlift.app', 14, y + 8);
  doc.text(`Page ${pageNum} of ${totalPages}`, 201, y + 8, { align: 'right' });
};

const addSectionHeader = (doc, text, y) => {
  doc.setFillColor(240, 240, 248);
  doc.rect(10, y - 5, 191, 10, 'F');
  doc.setDrawColor(...GOLD);
  doc.setLineWidth(0.5);
  doc.line(10, y - 5, 10, y + 5);
  doc.setTextColor(...DARK);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.text(text.toUpperCase(), 15, y + 1);
  return y + 12;
};

const addField = (doc, label, value, x, y, width = 85) => {
  doc.setTextColor(...GRAY);
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.text(label, x, y);
  doc.setTextColor(...DARK);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  const lines = doc.splitTextToSize(String(value || 'N/A'), width);
  doc.text(lines, x, y + 5);
  return y + 5 + (lines.length * 5);
};

// ==================== INVOICE PDF ====================
export const generateInvoicePDF = (invoice, companyProfile = {}) => {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const companyName = companyProfile.company_name || 'Southwest Cabs Elevator Services';

  addHeader(doc, companyName, `Invoice ${invoice.invoice_number || '#' + invoice.id}`,
    `Date: ${new Date(invoice.created_at || Date.now()).toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}`);

  let y = 52;

  // Status badge
  const statusColors = { paid: GREEN, pending: GOLD, overdue: RED, sent: [59, 130, 246] };
  const statusColor = statusColors[invoice.status] || GRAY;
  doc.setFillColor(...statusColor);
  doc.roundedRect(10, y, 30, 8, 2, 2, 'F');
  doc.setTextColor(...WHITE);
  doc.setFontSize(8);
  doc.setFont('helvetica', 'bold');
  doc.text((invoice.status || 'PENDING').toUpperCase(), 25, y + 5.5, { align: 'center' });

  y += 16;

  // Bill to / Invoice details
  y = addSectionHeader(doc, 'Bill To', y);
  addField(doc, 'Customer', invoice.customer_name, 14, y, 85);
  addField(doc, 'Invoice Number', invoice.invoice_number || 'INV-' + invoice.id, 110, y, 85);
  y += 8;
  addField(doc, 'Email', invoice.primary_contact_email || 'N/A', 14, y, 85);
  addField(doc, 'Due Date', invoice.due_date ? new Date(invoice.due_date).toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }) : 'Net 30', 110, y, 85);
  y += 16;

  // Line items table
  y = addSectionHeader(doc, 'Line Items', y);

  // Table header
  doc.setFillColor(...DARK);
  doc.rect(10, y, 191, 8, 'F');
  doc.setTextColor(...LIGHT);
  doc.setFontSize(8);
  doc.setFont('helvetica', 'bold');
  doc.text('Description', 14, y + 5.5);
  doc.text('Qty', 130, y + 5.5, { align: 'center' });
  doc.text('Rate', 158, y + 5.5, { align: 'right' });
  doc.text('Amount', 197, y + 5.5, { align: 'right' });
  y += 10;

  // Line items
  const lineItems = typeof invoice.line_items === 'string'
    ? JSON.parse(invoice.line_items || '[]')
    : (invoice.line_items || []);

  lineItems.forEach((item, i) => {
    if (i % 2 === 0) {
      doc.setFillColor(248, 248, 252);
      doc.rect(10, y - 2, 191, 8, 'F');
    }
    doc.setTextColor(...DARK);
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    const descLines = doc.splitTextToSize(item.description || 'Service', 110);
    doc.text(descLines, 14, y + 3);
    doc.text(String(item.qty || 1), 130, y + 3, { align: 'center' });
    doc.text('$' + parseFloat(item.rate || 0).toFixed(2), 158, y + 3, { align: 'right' });
    doc.text('$' + (parseFloat(item.qty || 1) * parseFloat(item.rate || 0)).toFixed(2), 197, y + 3, { align: 'right' });
    y += 8;
  });

  // Totals
  y += 4;
  doc.setDrawColor(220, 220, 230);
  doc.setLineWidth(0.3);
  doc.line(120, y, 201, y);
  y += 6;

  const totalsData = [
    ['Subtotal', '$' + parseFloat(invoice.amount || 0).toFixed(2)],
    ['Tax (8.25%)', '$' + parseFloat(invoice.tax || 0).toFixed(2)],
  ];

  totalsData.forEach(([label, value]) => {
    doc.setTextColor(...GRAY);
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.text(label, 158, y, { align: 'right' });
    doc.setTextColor(...DARK);
    doc.text(value, 197, y, { align: 'right' });
    y += 7;
  });

  // Total box
  doc.setFillColor(...DARK);
  doc.roundedRect(120, y, 81, 12, 2, 2, 'F');
  doc.setTextColor(...GOLD);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text('Total', 132, y + 8);
  doc.text('$' + parseFloat(invoice.total || 0).toFixed(2), 197, y + 8, { align: 'right' });
  y += 20;

  // Notes
  if (invoice.notes) {
    y = addSectionHeader(doc, 'Notes', y);
    doc.setTextColor(...GRAY);
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    const noteLines = doc.splitTextToSize(invoice.notes, 185);
    doc.text(noteLines, 14, y);
    y += noteLines.length * 5 + 8;
  }

  // Payment info
  y = addSectionHeader(doc, 'Payment Information', y);
  doc.setTextColor(...GRAY);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text('Please remit payment within the terms specified above. Contact us for payment arrangements.', 14, y);
  doc.setTextColor(...DARK);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.text(companyProfile.phone || '972-974-7005', 14, y + 7);
  doc.text(companyProfile.email || 'derald@swcabs.com', 60, y + 7);

  addFooter(doc, 1, 1);
  doc.save(`Invoice-${invoice.invoice_number || invoice.id}.pdf`);
};

// ==================== WORK ORDER PDF ====================
export const generateWorkOrderPDF = (workOrder, companyProfile = {}) => {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const companyName = companyProfile.company_name || 'Southwest Cabs Elevator Services';

  addHeader(doc, companyName, `Work Order ${workOrder.ticket_number || '#' + workOrder.id}`,
    `Created: ${new Date(workOrder.created_at || Date.now()).toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}`);

  let y = 52;

  // Priority badge
  const priorityColors = { emergency: RED, high: [245, 158, 11], medium: [59, 130, 246], low: GREEN };
  const pColor = priorityColors[workOrder.priority] || priorityColors.medium;
  doc.setFillColor(...pColor);
  doc.roundedRect(10, y, 35, 8, 2, 2, 'F');
  doc.setTextColor(...WHITE);
  doc.setFontSize(8);
  doc.setFont('helvetica', 'bold');
  doc.text((workOrder.priority || 'MEDIUM').toUpperCase() + ' PRIORITY', 27.5, y + 5.5, { align: 'center' });

  // Status badge
  const statusColors = { completed: GREEN, in_progress: GOLD, open: [59, 130, 246], cancelled: GRAY };
  const sColor = statusColors[workOrder.status] || GRAY;
  doc.setFillColor(...sColor);
  doc.roundedRect(50, y, 30, 8, 2, 2, 'F');
  doc.setTextColor(...WHITE);
  doc.text((workOrder.status || 'OPEN').toUpperCase().replace('_', ' '), 65, y + 5.5, { align: 'center' });

  y += 16;

  // Work order details
  y = addSectionHeader(doc, 'Work Order Details', y);
  addField(doc, 'Title', workOrder.title, 14, y, 85);
  addField(doc, 'Customer', workOrder.customer_name, 110, y, 85);
  y += 14;
  addField(doc, 'Assigned Technician', workOrder.assigned_technician || 'Unassigned', 14, y, 85);
  addField(doc, 'Scheduled Date', workOrder.scheduled_date ? new Date(workOrder.scheduled_date).toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric', year: 'numeric' }) : 'TBD', 110, y, 85);
  y += 16;

  if (workOrder.description) {
    y = addSectionHeader(doc, 'Description', y);
    doc.setTextColor(...DARK);
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    const descLines = doc.splitTextToSize(workOrder.description, 185);
    doc.text(descLines, 14, y);
    y += descLines.length * 5 + 10;
  }

  // Work log
  if (workOrder.work_performed) {
    y = addSectionHeader(doc, 'Work Performed', y);
    doc.setTextColor(...DARK);
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    const workLines = doc.splitTextToSize(workOrder.work_performed, 185);
    doc.text(workLines, 14, y);
    y += workLines.length * 5 + 10;
  }

  // Signature block
  y = Math.max(y, 220);
  y = addSectionHeader(doc, 'Sign Off', y);

  doc.setDrawColor(180, 180, 190);
  doc.setLineWidth(0.3);

  // Technician signature
  doc.rect(14, y, 80, 20);
  doc.setTextColor(...GRAY);
  doc.setFontSize(8);
  doc.text('Technician Signature', 14, y + 25);
  doc.text(workOrder.assigned_technician || 'Technician', 14, y + 30);

  // Customer signature
  doc.rect(110, y, 80, 20);
  doc.text('Customer Signature', 110, y + 25);
  doc.text('Date: _______________', 110, y + 30);

  addFooter(doc, 1, 1);
  doc.save(`WorkOrder-${workOrder.ticket_number || workOrder.id}.pdf`);
};

// ==================== PROPOSAL PDF ====================
export const generateProposalPDF = (prospect, proposalText, companyProfile = {}) => {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const companyName = companyProfile.company_name || 'Southwest Cabs Elevator Services';

  addHeader(doc, companyName, 'Elevator Service Proposal',
    new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }));

  let y = 52;

  // Prospect info
  y = addSectionHeader(doc, 'Prepared For', y);
  addField(doc, 'Building / Company', prospect.name, 14, y, 85);
  addField(doc, 'Address', prospect.address || prospect.city || 'N/A', 110, y, 85);
  y += 14;
  if (prospect.primary_contact) {
    addField(doc, 'Contact', prospect.primary_contact, 14, y, 85);
    y += 14;
  }
  y += 4;

  // Proposal content
  y = addSectionHeader(doc, 'Proposal', y);

  const lines = (proposalText || '').split('\n');
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');

  lines.forEach(line => {
    if (y > 270) {
      addFooter(doc, doc.internal.getCurrentPageInfo().pageNumber, '?');
      doc.addPage();
      addHeader(doc, companyName, 'Elevator Service Proposal (continued)', '');
      y = 52;
    }

    const trimmed = line.trim();
    if (!trimmed) { y += 4; return; }

    // Section headers in proposal
    if (trimmed.startsWith('#') || trimmed.match(/^[A-Z][A-Z\s]+:$/)) {
      doc.setFillColor(240, 240, 248);
      doc.rect(10, y - 4, 191, 8, 'F');
      doc.setTextColor(...DARK);
      doc.setFontSize(9);
      doc.setFont('helvetica', 'bold');
      doc.text(trimmed.replace(/^#+\s*/, ''), 14, y + 1);
      doc.setFont('helvetica', 'normal');
      y += 10;
    } else if (trimmed.startsWith('- ') || trimmed.startsWith('• ')) {
      doc.setTextColor(...DARK);
      doc.setFontSize(9);
      doc.setTextColor(...GOLD);
      doc.text('•', 14, y);
      doc.setTextColor(...DARK);
      const bulletLines = doc.splitTextToSize(trimmed.replace(/^[-•]\s*/, ''), 178);
      doc.text(bulletLines, 20, y);
      y += bulletLines.length * 5 + 2;
    } else {
      doc.setTextColor(...DARK);
      doc.setFontSize(9);
      const textLines = doc.splitTextToSize(trimmed, 185);
      doc.text(textLines, 14, y);
      y += textLines.length * 5 + 2;
    }
  });

  // Signature block
  if (y > 240) {
    addFooter(doc, doc.internal.getCurrentPageInfo().pageNumber, '?');
    doc.addPage();
    addHeader(doc, companyName, 'Elevator Service Proposal — Acceptance', '');
    y = 52;
  } else {
    y = Math.max(y + 10, 220);
  }

  y = addSectionHeader(doc, 'Acceptance', y);
  doc.setTextColor(...GRAY);
  doc.setFontSize(9);
  doc.text('By signing below, you agree to the terms outlined in this proposal.', 14, y);
  y += 12;

  doc.setDrawColor(180, 180, 190);
  doc.setLineWidth(0.3);
  doc.rect(14, y, 80, 20);
  doc.setFontSize(8);
  doc.text('Authorized Signature', 14, y + 25);
  doc.text('Date: _______________', 14, y + 30);

  doc.rect(110, y, 80, 20);
  doc.text(companyName, 110, y + 25);
  doc.text('Jeremy Wilson, Founder', 110, y + 30);

  const totalPages = doc.internal.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    addFooter(doc, i, totalPages);
  }

  doc.save(`Proposal-${prospect.name?.replace(/\s+/g, '-') || 'Prospect'}.pdf`);
};
